apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-backend
  namespace: rental-games
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: rental-backend
  template:
    metadata:
      labels:
        app: rental-backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
          command:
            - sh
            - -c
            - |
              until pg_isready -h "$DB_HOST" -p "$DB_PORT" -U "$PGUSER"; do
                echo "Czekam na PostgreSQL..."; sleep 2;
              done
      containers:
        - name: rental-backend
          resources:
            requests:
              memory: "256Mi"  # ile K8s rezerwuje dla Poda przy schedulingu
              cpu: "250m"       # 250 milicores = 1/4 rdzenia
            limits:
              memory: "512Mi"  # maksimum — przekroczenie = OOMKill
              cpu: "500m"
          image: rental-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5


