apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: rental-games
type: Opaque
data:
  # "postgres" w base64
  POSTGRES_USER: cG9zdGdyZXM=
  # "postgres" w base64
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # "rental-game-db" w base64
  POSTGRES_DB: cmVudGFsLWdhbWUtZGI=

